# Generated by Django 4.1.10 on 2026-03-10 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ComplaintCategory', '0002_complaintcategory_profession'),
        ('students', '0001_initial'),
        ('hostel_management', '0003_alter_room_room_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('complaint_img', models.ImageField(blank=True, null=True, upload_to='complaint_pics/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In-Progress', 'In-Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ComplaintCategory.complaintcategory')),
                ('room_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_management.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
