# Generated by Django 4.1.10 on 2026-01-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('roll_no', models.CharField(max_length=10, unique=True)),
                ('student_class', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('contact', models.CharField(max_length=11)),
                ('hostel_room', models.CharField(max_length=3)),
            ],
        ),
    ]
