# Generated by Django 5.0.7 on 2026-01-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('principal', 'Principal'), ('admin', 'Admin'), ('accountant', 'Accountant'), ('librarian', 'Librarian'), ('it', 'IT Support'), ('guard', 'Guard'), ('cleaner', 'Cleaner')], max_length=20)),
                ('contact', models.CharField(max_length=15)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='staff_pictures/')),
            ],
        ),
    ]
