# Generated by Django 4.1.10 on 2026-02-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=15)),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=15)),
                ('food_item', models.CharField(choices=[('Daal Chawal', 'Daal Chawal'), ('Chicken Karahi', 'Chicken Karahi'), ('Aloo Gobi', 'Aloo Gobi'), ('Biryani', 'Biryani'), ('Anda Paratha', 'Anda Paratha'), ('Omelette', 'Omelette'), ('Haleem', 'Haleem'), ('Sabzi Mix', 'Sabzi Mix')], max_length=100)),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('day', 'meal_type')},
            },
        ),
    ]
