# Generated by Django 4.1.10 on 2026-02-24 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Mess', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messmenu',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='messmenu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messmenu',
            name='custom_food_item',
            field=models.CharField(blank=True, help_text="Only fill if 'Custom' is selected in food item", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='messmenu',
            name='food_item',
            field=models.CharField(choices=[('Daal Chawal', 'Daal Chawal'), ('Chicken Karahi', 'Chicken Karahi'), ('Aloo Gobi', 'Aloo Gobi'), ('Biryani', 'Biryani'), ('Anda Paratha', 'Anda Paratha'), ('Omelette', 'Omelette'), ('Haleem', 'Haleem'), ('Custom', '--- Other (Write Custom) ---')], max_length=100),
        ),
        migrations.AlterField(
            model_name='messmenu',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
