# Generated by Django 4.2.20 on 2026-03-18 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='user',
        ),
        migrations.AddField(
            model_name='signup',
            name='email',
            field=models.EmailField(default='none@example.com', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='cnic',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('expires_at', models.DateField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.signup')),
            ],
        ),
    ]
