# Generated by Django 5.0.7 on 2026-01-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='user',
        ),
        migrations.AddField(
            model_name='signup',
            name='email',
            field=models.EmailField(default='none@example.com', max_length=40, unique=True),
        ),
    ]
