# Generated by Django 4.1.10 on 2026-01-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_signup_user_signup_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='cnic',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
