# Generated by Django 4.1.10 on 2026-03-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintCategory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintcategory',
            name='profession',
            field=models.CharField(choices=[('Electrician', 'Electrician'), ('Plumber', 'Plumber'), ('Carpenter', 'Carpenter'), ('Mason', 'Mason (Mistry)'), ('Painter', 'Painter'), ('AC Technician', 'AC Technician'), ('Gardener', 'Gardener'), ('Cleaner', 'Janitor/Cleaner'), ('Welder', 'Welder'), ('IT Specialist', 'IT/Network Specialist')], default='Other', max_length=50),
        ),
    ]
